In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,6]

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 6])

In [4]:
nested_list = [[1,2],[3,4],[5,6]]

In [5]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.rand(2)

array([0.9607273 , 0.36022662])

# +ve random 0 to 1

In [21]:
np.random.rand(3,4)

array([[0.21445346, 0.82793875, 0.99378282, 0.29784285],
       [0.35679827, 0.82172792, 0.12090407, 0.64247554],
       [0.55931107, 0.13192463, 0.4387592 , 0.05631901]])

# -ve/+ve random centred 0

In [22]:
np.random.randn(3,4)

array([[-0.71270795,  0.11886732,  0.7947732 ,  0.47652275],
       [-0.55188658, -0.90310045,  1.54905385, -1.4328849 ],
       [-0.15839873,  0.3285683 ,  2.13918884, -0.96331396]])

#Random Int

In [23]:
np.random.randint(1,100)

90

In [24]:
np.random.randint(1,100,10)

array([27, 94, 82, 26, 19, 12, 95, 64, 29, 99])

In [25]:
np.random.randint(1,100,(2,4))

array([[61, 93, 24, 98],
       [92, 26,  4, 85]])

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr = np.random.randint(0,50,10)

In [38]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [39]:
arr.shape

(25,)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [42]:
ranarr.max()

39

In [43]:
ranarr.min()

2

In [44]:
ranarr.argmax()

7

In [45]:
ranarr.argmin()

9

In [47]:
ranarr.dtype

dtype('int32')

In [49]:
arr.dtype

dtype('int32')